const cakes = [
  {
    _id: "1",
    name: "Yellow Butter Cake",
    image: "/images/yellow_butter_cake.jpeg",
    description:
      "The cake combines the soft texture of white cake with the buttery flavor of yellow cake.",
    shop: "Arcade Bakery",
    category: "Food",
    price: 39.9,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Pound Cake",
    image: "/images/pound_cake.jpeg",
    description:
      "Named because it's made with a pound of each of the main ingredients (flour, butter, and sugar), this cake doesn’t rise much while baking, and the texture is very dense.",
    shop: "b.patisserie",
    category: "Food",
    price: 20.55,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Red Velvet Cake",
    image: "/images/red_velvet_cake.jpeg",
    description:
      "Made with either butter or oil, red velvet cake's color classically comes from the reaction of buttermilk and cocoa powder.",
    shop: "Babettes Artisan Breads",
    category: "Food",
    price: 41.5,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Carrot Cake",
    image: "/images/carrot_cake.jpeg",
    description:
      "Leavened with baking soda and baking powder, this shortened cake uses oil as its main fat rather than butter. The addition of grated carrots makes the cake extra moist. Carrot cake is also flavored with warm spices and frosted with a rich cream cheese frosting. Pecans or walnuts are optional!",
    shop: "Baker Miller",
    category: "Food",
    price: 15.8,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Sponge Cake",
    image: "/images/sponge_cake.jpeg",
    description:
      "This is a foam-style cake that has no artificial leaveners (baking powder or baking soda). It gets its volume solely from whipped eggs —either whole eggs or simply whites.",
    shop: "The Bakery at Fat Rice",
    category: "Food",
    price: 40.95,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Genoise Cake",
    image: "/images/genoise_cake.jpg",
    description:
      "Genoise is what a sponge cake is called in Italy or France. In this cake, egg yolks, whites and sugar are beaten together until mousse-like. Next, flour, and either oil or butter, are folded in. ",
    shop: "Bakery Lorraine",
    category: "Food",
    price: 35.4,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Chiffon Cake",
    image: "/images/chiffon_cake.jpeg",
    description:
      "Chiffon cake is a cross between a sponge and oil cake. The addition of oil gives it a richness similar to a shortened cake, and whipped egg whites and baking powder make it light and airy.",
    shop: "Bakery Nouveau",
    category: "Food",
    price: 24.7,
    countInStock: 8,
    rating: 4.2,
    numReviews: 3,
  },
  {
    _id: "8",
    name: "Upside Down Cake",
    image: "/images/upside_down_cake.jpg",
    description:
      "The classic version of this butter style cake is traditionally made with pineapple, but can be made with many varieties of fruits, including plums, peaches, blueberries, or pears.",
    shop: "CH Patisserie",
    category: "Food",
    price: 18.5,
    countInStock: 5,
    rating: 4.6,
    numReviews: 15,
  },
  {
    _id: "9",
    name: "Flourless Cake",
    image: "/images/flourless_cake.jpg",
    description:
      "This category includes both baked (think cheese cake or flourless chocolate) or unbaked (like mousse or unbaked cheesecakes) varieties. ",
    shop: "CH Patisserie",
    category: "Food",
    price: 32,
    countInStock: 6,
    rating: 4.1,
    numReviews: 22,
  },
];

module.exports = cakes;
