export const CAKE_LIST_REQUEST = "CAKE_LIST_REQUEST";
export const CAKE_LIST_SUCCESS = "CAKE_LIST_SUCCESS";
export const CAKE_LIST_ERROR = "CAKE_LIST_ERROR";

export const CAKE_DETAILS_REQUEST = "CAKE_DETAILS_REQUEST ";
export const CAKE_DETAILS_SUCCESS = "CAKE_DETAILS_SUCCESS";
export const CAKE_DETAILS_ERROR = "CAKE_DETAILS_ERROR";



export const CAKE_DELETE_REQUEST = 'CAKE_DELETE_REQUEST'
export const CAKE_DELETE_SUCCESS = 'CAKE_DELETE_SUCCESS'
export const CAKE_DELETE_FAIL = 'CAKE_DELETE_FAIL'

export const CAKE_CREATE_REQUEST = 'CAKE_CREATE_REQUEST'
export const CAKE_CREATE_SUCCESS = 'CAKE_CREATE_SUCCESS'
export const CAKE_CREATE_FAIL = 'CAKE_CREATE_FAIL'
export const CAKE_CREATE_RESET = 'CAKE_CREATE_RESET'

export const CAKE_UPDATE_REQUEST = 'CAKE_UPDATE_REQUEST'
export const CAKE_UPDATE_SUCCESS = 'CAKE_UPDATE_SUCCESS'
export const CAKE_UPDATE_FAIL = 'CAKE_UPDATE_FAIL'
export const CAKE_UPDATE_RESET = 'CAKE_UPDATE_RESET'

export const CAKE_CREATE_REVIEW_REQUEST = 'CAKE_CREATE_REVIEW_REQUEST'
export const CAKE_CREATE_REVIEW_SUCCESS = 'CAKE_CREATE_REVIEW_SUCCESS'
export const CAKE_CREATE_REVIEW_FAIL = 'CAKE_CREATE_REVIEW_FAIL'
export const CAKE_CREATE_REVIEW_RESET = 'CAKE_CREATE_REVIEW_RESET'

export const CAKE_TOP_REQUEST = 'CAKE_TOP_REQUEST'
export const CAKE_TOP_SUCCESS = 'CAKE_TOP_SUCCESS'
export const CAKE_TOP_FAIL = 'CAKE_TOP_FAIL'