export const CAKE_LIST_REQUEST = "CAKE_LIST_REQUEST";
export const CAKE_LIST_SUCCESS = "CAKE_LIST_SUCCESS";
export const CAKE_LIST_ERROR = "CAKE_LIST_ERROR";

export const SINGLE_CAKE_REQUEST = "SINGLE_CAKE_REQUEST ";
export const SINGLE_CAKE_SUCCESS = "SINGLE_CAKE_SUCCESS";
export const SINGLE_CAKE_ERROR = "SINGLE_CAKE_ERROR";
